package content

const (
	CustomerIdName     = "customer_id"
	StartTimeName      = "start_time"
	DurationName       = "duration_ms"
	DurationStrName    = "duration_str"
	TrafficName        = "traffic"
	RegionName         = "region"
	ZoneName           = "zone"
	SubZoneName        = "sub_zone"
	ServiceName        = "service"
	InstanceIdName     = "instance_id"
	RouteNameName      = "route_name"
	RequestIdName      = "request_id"
	UrlName            = "url"
	ProtocolName       = "protocol"
	MethodName         = "method"
	HostName           = "host"
	PathName           = "path"
	StatusCodeName     = "status_code"
	BytesSentName      = "bytes_sent"
	StatusFlagsName    = "status_flags"
	TimeoutName        = "timeout"
	RateLimitName      = "rate_limit"
	RateBurstName      = "rate_burst"
	RetryName          = "retry"
	RetryRateLimitName = "retry_rate_limit"
	RetryRateBurstName = "retry_rate_burst"
	FailoverName       = "failover"
	ProxyName          = "proxy"
)
